stages:
  - build
  - test
  - deploy

# Étape 1 : Build
build:
  stage: build
  script:
    - echo "Building the application..."
    - docker-compose build
  only:
    - develop

# Étape 2 : Tests
test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm test
  only:
    - develop

# Étape 3 : Déploiement
deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - ssh -i $SSH_PRIVATE_KEY user@server 'docker stack deploy -c docker-compose.yml ecommerce_stack'
  only:
    - main
